export default {
  de: {
    localeISO: "de-DE",
    appName: "pe ‧‧ tra",
    tagline: "periodentracker. privat & anonym.",
    calendar: "Kalender",
    predictions: "Vorhersagen",
    analysis: "Analyse",
    weekDays: ['So', 'Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa'],
    overdueWarning: "Überfällig seit {days} Tagen",
    period: "Periode",
    symptom: "Symptom",
    predictedPeriod: "Vorhergesagte Periode",
    nextPeriod: "Nächste Periode",
    ovulation: "Eisprung",
    fertileDays: "Fruchtbare Tage",
    cycleLength: "Zykluslänge: {days} Tage",
    unknown: "Unbekannt",
    noData: "Noch keine Daten verfügbar",
    yourStats: "Deine Zyklusstatistiken",
    cycleDays: "Tage Zyklus",
    cyclesTracked: "Zyklen getrackt",
    frequentSymptoms: "Häufigste Symptome",
    addPeriod: "Periode hinzufügen",
    startDate: "Startdatum",
    length: "Dauer (Tage)",
    cancel: "Abbrechen",
    save: "Speichern",
    addSymptom: "Symptom hinzufügen",
    date: "Datum",
    pickSymptom: "Symptom auswählen"
  },
  en: {
    localeISO: "en-US",
    appName: "pe ‧‧ tra",
    tagline: "periode tracker. private & anonymous.",
    calendar: "Calendar",
    predictions: "Predictions",
    analysis: "Analysis",
    weekDays: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
    overdueWarning: "Overdue for {days} days",
    period: "Period",
    symptom: "Symptom",
    predictedPeriod: "Predicted Period",
    nextPeriod: "Next Period",
    ovulation: "Ovulation",
    fertileDays: "Fertile Days",
    cycleLength: "Cycle Length: {days} days",
    unknown: "Unknown",
    noData: "No data available yet",
    yourStats: "Your Stats",
    cycleDays: "cycle days",
    cyclesTracked: "cycles tracked",
    frequentSymptoms: "Most Frequent Symptoms",
    addPeriod: "Add Period",
    startDate: "Start Date",
    length: "Length (Days)",
    cancel: "Cancel",
    save: "Save",
    addSymptom: "Add Symptom",
    date: "Date",
    pickSymptom: "Pick Symptom"
  }
};