export default {
  de: {
    localeISO: "de-DE",
    appName: "pe ‧‧ tra",
    tagline: "periodentracker. privat & anonym.",
    calendar: "Kalender",
    predictions: "Vorhersagen",
    analysis: "Analyse",
    weekDays: ['Mo', 'Di', 'Mi', 'Do', 'Fr', 'Sa', 'So'],
    overdueWarning: "Überfällig seit {days} Tagen",
    cycleDay: 'Zyklustag {day}',
    today: 'Heute',
    period: "Periode",
    symptom: "Symptom",
    predictedPeriod: "Vorhergesagte Periode",
    possibleSymptoms: 'Mögliche Symptome heute',
    nextPeriod: "Nächste Periode",
    ovulation: "Eisprung",
    fertileDays: "Fruchtbare Tage",
    cycleLength: "Zykluslänge: {days} Tage",
    days: "Tage",
    unknown: "Unbekannt",
    noData: "Noch keine Daten verfügbar",
    yourStats: "Deine Zyklusstatistiken",
    cycleDays: "Tage Zyklus",
    cyclesTracked: "Zyklen getrackt",
    frequentSymptoms: "Häufigste Symptome",
    addPeriod: "Periode hinzufügen",
    editPeriod: "Periode bearbeiten",
    deletePeriod: "Periode löschen",
    startDate: "Startdatum",
    length: "Dauer (Tage)",
    cancel: "Abbrechen",
    save: "Speichern",
    addSymptom: "Symptom hinzufügen",
    date: "Datum",
    editDay: "Tag bearbeiten",
    pickSymptom: "Symptom auswählen",
    phaseLabels: {
      period_day1: 'Erster Periodentag',
      period: 'Periode',
      follicular: 'Follikelphase',
      pre_ovulation: 'Vor dem Eisprung',
      ovulation: 'Eisprung',
      post_ovulation: 'Nach dem Eisprung',
      early_luteal: 'Frühe Lutealphase',
      late_luteal: 'Späte Lutealphase',
    },
    phaseIntroTypical: 'Typische Symptome in dieser Phase ({phase}):',
    phaseIntroByDay: 'An Tag {day} hast du oft:',
    phaseIntroTracked: 'In dieser Phase ({phase}) hast du oft:',
  },
  en: {
    localeISO: "en-US",
    appName: "pe ‧‧ tra",
    tagline: "period tracker. private & anonymous.",
    calendar: "Calendar",
    predictions: "Predictions",
    analysis: "Analysis",
    weekDays: ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su'],
    overdueWarning: "Overdue for {days} days",
    cycleDay: 'Cycle day {day}',
    today: 'Today',
    period: "Period",
    symptom: "Symptom",
    predictedPeriod: "Predicted Period",
    possibleSymptoms: 'Possible Symptoms Today',
    nextPeriod: "Next Period",
    ovulation: "Ovulation",
    fertileDays: "Fertile Days",
    cycleLength: "Cycle Length: {days} days",
    days: "days",
    unknown: "Unknown",
    noData: "No data available yet",
    yourStats: "Your Stats",
    cycleDays: "cycle days",
    cyclesTracked: "cycles tracked",
    frequentSymptoms: "Most Frequent Symptoms",
    addPeriod: "Add Period",
    editPeriod: "Edit Period",
    deletePeriod: "Delete Period",
    startDate: "Start Date",
    length: "Length (Days)",
    cancel: "Cancel",
    save: "Save",
    addSymptom: "Add Symptom",
    date: "Date",
    editDay: "Edit Day",
    pickSymptom: "Pick Symptom",
    phaseLabels: {
      period_day1: 'First Day of your Period',
      period: 'Period',
      follicular: 'Follicular Phase',
      pre_ovulation: 'Pre-Ovulation',
      ovulation: 'Ovulation',
      post_ovulation: 'Post-Ovulation',
      early_luteal: 'Early Luteal Phase',
      late_luteal: 'Late Luteal Phase',
    },
    phaseIntroTypical: 'Typical symptoms during this phase ({phase}):',
    phaseIntroByDay: 'On day {day} you often experience:',
    phaseIntroTracked: 'During this phase ({phase}) you often experience:',
  }
};